# -*- coding: utf-8 -*-
"""predictive_customer_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyX6RJHSLYxocDaEFz-zKH9duIrrmcoD
"""

import pandas as pd
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate synthetic data
n = 500

data = {
    "CustomerID": np.arange(1000, 1000 + n),
    "Age": np.random.randint(18, 70, size=n),
    "Gender": np.random.choice(["Male", "Female"], size=n),
    "AnnualIncome": np.random.randint(15, 150, size=n),
    "SpendingScore": np.random.randint(1, 100, size=n)
}

df = pd.DataFrame(data)

# Generate a synthetic binary target: Purchase Likelihood
df["PurchaseLikelihood"] = ((df["SpendingScore"] > 50) & (df["AnnualIncome"] > 50)).astype(int)

import os

# Create the directory if it doesn't exist
if not os.path.exists("data"):
    os.makedirs("data")

# Save to CSV
df.to_csv("data/sample_customer_data.csv", index=False)
print("✅ Synthetic dataset saved at data/sample_customer_data.csv")

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import joblib

# Load data from the locally generated CSV
df = pd.read_csv("data/sample_customer_data.csv")

# Select and rename columns to match the original code's intended structure
# Assuming the synthetic data has similar column names or structure
# Based on the generated data structure, I'll select the relevant columns
df = df[["Age", "Gender", "AnnualIncome", "SpendingScore", "PurchaseLikelihood"]]
# The column names in the synthetic data already match the desired names, so no renaming is needed here.
# df = df.rename(columns={"Annual Income ($)": "AnnualIncome", "Spending Score (1-100)": "SpendingScore"})

df = df.dropna().copy() # Keep this step in case of any missing values in synthetic data

# The target variable 'PurchaseLikelihood' is already present in the synthetic data.
# If you were using the external data, you might need to create it as originally intended.
# df["PurchaseLikelihood"] = ((df["SpendingScore"] > 50) & (df["AnnualIncome"] > 50)).astype(int)

df["PurchaseLikelihood"] = ((df["SpendingScore"] > 50) & (df["AnnualIncome"] > 50)).astype(int)

# Encode gender
df["Gender"] = LabelEncoder().fit_transform(df["Gender"])

# Train model
X = df[["Age", "Gender", "AnnualIncome", "SpendingScore"]]
y = df["PurchaseLikelihood"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

#Save model
joblib.dump(model, "customer_model.pkl")
print("✅ Model saved as customer_model.pkl")

!pip install streamlit
!pip install pyngrok

pip install joblib

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load("../models/customer_model.pkl")

st.title("🛍️ Customer Purchase Prediction")

age = st.slider("Age", 18, 70, 30)
gender = st.selectbox("Gender", ["Male", "Female"])
income = st.slider("Annual Income (k$)", 15, 150, 60)
score = st.slider("Spending Score", 1, 100, 50)

# Preprocessing input
gender_num = 1 if gender == "Male" else 0
features = pd.DataFrame([[age, gender_num, income, score]],
                        columns=["Age", "Gender", "AnnualIncome", "SpendingScore"])

# Prediction
if st.button("Predict Purchase Likelihood"):
    pred = model.predict(features)[0]
    result = "✅ Likely to Purchase" if pred == 1 else "❌ Not Likely to Purchase"
    st.subheader(result)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dashboard_app.py
# import streamlit as st
# import pandas as pd
# import joblib
# 
# st.title("🛍️ Customer Purchase Prediction")
# 
# age = st.slider("Age", 18, 70, 30)
# gender = st.selectbox("Gender", ["Male", "Female"])
# income = st.slider("Annual Income (k$)", 15, 150, 60)
# score = st.slider("Spending Score", 1, 100, 50)
# 
# gender_num = 1 if gender == "Male" else 0
# features = pd.DataFrame([[age, gender_num, income, score]],
#                         columns=["Age", "Gender", "AnnualIncome", "SpendingScore"])
# 
# model = joblib.load("customer_model.pkl")
# 
# if st.button("Predict Purchase Likelihood"):
#     pred = model.predict(features)[0]
#     result = "✅ Likely to Purchase" if pred == 1 else "❌ Not Likely to Purchase"
#     st.subheader(result)
#

from pyngrok import ngrok

# Kill any existing tunnels
ngrok.kill()

from pyngrok import ngrok
from google.colab import userdata

# Get the authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get("NGROK_AUTH_TOKEN")

# Configure pyngrok with the authtoken
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

print("✅ ngrok authtoken configured.")

from pyngrok import ngrok
from google.colab import userdata
# Kill any existing tunnels
# Get the authtoken from Colab secrets
NGROK_AUTH_TOKEN = userdata.get("NGROK_AUTH_TOKEN")

# Configure pyngrok with the authtoken
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

print("✅ ngrok authtoken configured.")

# Install dependencies
!pip install streamlit pyngrok --quiet

# Kill existing tunnels if any
from pyngrok import ngrok
ngrok.kill()

# Create new tunnel for port 8501
public_url = ngrok.connect(8501)
print(f"🔗 Streamlit is live at: {public_url}")

# Write Streamlit app
with open("dashboard_app.py", "w") as f:
    f.write('''
import streamlit as st
import pandas as pd
import joblib

st.title("🛍️ Customer Purchase Prediction")

age = st.slider("Age", 18, 70, 30)
gender = st.selectbox("Gender", ["Male", "Female"])
income = st.slider("Annual Income (k$)", 15, 150, 60)
score = st.slider("Spending Score", 1, 100, 50)

gender_num = 1 if gender == "Male" else 0
features = pd.DataFrame([[age, gender_num, income, score]],
                        columns=["Age", "Gender", "AnnualIncome", "SpendingScore"])

model = joblib.load("customer_model.pkl")

if st.button("Predict Purchase Likelihood"):
    pred = model.predict(features)[0]
    result = "✅ Likely to Purchase" if pred == 1 else "❌ Not Likely to Purchase"
    st.subheader(result)
''')

# Run Streamlit app in background
!streamlit run dashboard_app.py &>/dev/null &

